# config.yml

backend:
  name: github # Use 'github' as the backend if you're directly connecting to GitHub
  repo: your-username/your-repo-name # Replace with your GitHub username and repository name
  branch: main # The branch you want to update, usually 'main'
  auth_scope: repo, workflow
media_folder: "assets/images" # Folder where uploaded media files will be stored
public_folder: "/assets/images" # Public URL of the media folder
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" } # Optionally add an image field
