# config.yml

backend:
  name: git-gateway
  auth_scope: "user:email"
  # name: github # Use 'github' as the backend if you're directly connecting to GitHub
  # repo: EliseAur/jekyll-decap-test # Replace with your GitHub username and repository name
  # branch: main # The branch you want to update, usually 'main'
  # auth_scope: repo, workflow
media_folder: "assets/images" # Folder where uploaded media files will be stored
public_folder: "/assets/images" # Public URL of the media folder
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", display_fields: [display_name], search_fields: [display_name], value_field: "name" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" } # Optionally add an image field
  - name: "authors"
    label: "Authors"
    folder: "_authors/"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Short Name", name: "name", widget: "string" }
      - { label: "Display Name", name: "display_name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "hidden", default: "about" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "about" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
